### PR TITLE
Update images in validator guide

### PR DESCRIPTION
**Pull request by laboon**
I updated the images and made some minor changes to the validator guide to more closely match what the user would see.

There are more images to update but I think this is good as-is for this PR as it will allow Joe to continue working without dealing with merges later (and I've got a talk to give shortly).

I also did a quick grep to make sure there were no references to Session Account hanging around, but did not see any.

```bash
(678) ~/web3/userguide/docs $ grep -R "[Ss]ession [Kk]ey" . | wc
       6     147    1104
(679) ~/web3/userguide/docs $ grep -R "[Ss]ession [Aa]ccount" . | wc
       0       0       0
```

### CODE REVIEW

**Comment by joshua-mir** [comment]
Should this be merged now or after Joe starts making PRs?

**Comment by laboon** [comment]
Before.  I just talked with him on Riot, this shouldn't impact what he's doing and he'll build on top of it (and not have to deal with any merges).

**Comment by laboon** [comment]
Err, "before" should be "now"

**Comment by joshua-mir** [comment]
(I was concerned that the images wouldn't render on the compiled site but it looks like they do 👍)

**Pull request merged**
